name: Process Match Dates

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'process-all'
        type: choice
        options:
          - process-all
          - process-batch
          - merge
      batchFile:
        description: 'Batch file to process (only for process-batch)'
        required: false
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          if [ "${{ github.event.inputs.action }}" == "process-all" ]; then
            BATCH_FILES=$(ls -1 batches/ | grep "batch_.*\.json" | jq -R -s -c 'split("\n") | map(select(length > 0))')
            echo "matrix=${BATCH_FILES}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.action }}" == "process-batch" ]; then
            echo "matrix=[\"${{ github.event.inputs.batchFile }}\"]" >> $GITHUB_OUTPUT
          else
            echo "matrix=[]" >> $GITHUB_OUTPUT
          fi

  process-batches:
    needs: setup
    if: github.event.inputs.action == 'process-all' || github.event.inputs.action == 'process-batch'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batchFile: ${{ fromJson(needs.setup.outputs.matrix) }}
      max-parallel: 5
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Process batch
        run: node fix-match-dates.js process ${{ matrix.batchFile }}

      - name: Commit results
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git pull --rebase origin ${{ github.ref }}
          git add results/
          git commit -m "Process batch ${{ matrix.batchFile }} [$(date -u +'%Y-%m-%dT%H:%M:%SZ')]" || echo "No changes to commit"
          git push origin ${{ github.ref }}

  merge-results:
    if: github.event.inputs.action == 'merge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Merge results
        run: node fix-match-dates.js merge

      - name: Commit merged results
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add dateFixes.json blocked.json
          git commit -m "Merge all batch results [$(date -u +'%Y-%m-%dT%H:%M:%SZ')]" || echo "No changes to commit"
          git push origin ${{ github.ref }}
