name: Process All Match Dates

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'process-all'
        type: choice
        options:
          - process-all
          - process-batch
          - merge
      batchFile:
        description: 'Batch file to process (only for process-batch)'
        required: false
        type: string

jobs:
  count-batches:
    if: github.event.inputs.action == 'process-all'
    runs-on: ubuntu-latest
    outputs:
      batch_files: ${{ steps.get_batches.outputs.batches }}

    steps:
      - uses: actions/checkout@v3

      - name: Get batch files
        id: get_batches
        run: |
          BATCH_FILES=$(ls -1 batches/ | grep "batch_.*\.json" | tr '\n' ' ')
          echo "batches=${BATCH_FILES}" >> $GITHUB_OUTPUT
          echo "Found these batch files: ${BATCH_FILES}"

  process-all:
    if: github.event.inputs.action == 'process-all'
    needs: count-batches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch_file: ${{ fromJson('["' + join(split(needs.count-batches.outputs.batch_files, ' '), '","') + '"]') }}
      max-parallel: 5
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Process batch
        run: |
          node fix-match-dates.js process ${{ matrix.batch_file }}
          echo "Processed ${{ matrix.batch_file }}"

      - name: Commit results
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git pull origin ${{ github.ref }} --rebase
          git add results/
          git commit -m "Process batch ${{ matrix.batch_file }} [$(date -u +'%Y-%m-%dT%H:%M:%SZ')]" || echo "No changes to commit"
          git push

  process-single-batch:
    if: github.event.inputs.action == 'process-batch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Process batch
        run: node fix-match-dates.js process ${{ github.event.inputs.batchFile }}

      - name: Commit results
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add results/
          git commit -m "Process batch ${{ github.event.inputs.batchFile }} [$(date -u +'%Y-%m-%dT%H:%M:%SZ')]" || echo "No changes to commit"
          git push

  merge-results:
    if: github.event.inputs.action == 'merge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Merge results
        run: node fix-match-dates.js merge

      - name: Commit merged results
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add dateFixes.json blocked.json
          git commit -m "Merge all batch results [$(date -u +'%Y-%m-%dT%H:%M:%SZ')]" || echo "No changes to commit"
          git push
