name: Process Match Dates

on:
  workflow_dispatch:
    inputs:
      batchStart:
        description: 'Starting batch number'
        required: true
        default: '1'
        type: string
      batchEnd:
        description: 'Ending batch number'
        required: true
        default: '10'
        type: string
      action:
        description: 'Action to perform'
        required: true
        default: 'process'
        type: choice
        options:
          - process
          - merge

jobs:
  process-dates:
    if: github.event.inputs.action == 'process'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch_number: ${{ fromJson(format('[{0}]', join(range(fromJson(github.event.inputs.batchStart), add(fromJson(github.event.inputs.batchEnd), 1)), ','))) }}
      # Process up to 10 batches in parallel - adjust as needed
      max-parallel: 5
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Determine batch filename
        id: batch_file
        run: |
          # Find the total number of batches from any existing batch file
          BATCH_FILE=$(ls batches/ | grep -E "batch_[0-9]+_of_[0-9]+" | head -1)
          TOTAL_BATCHES=$(echo $BATCH_FILE | sed -E 's/batch_[0-9]+_of_([0-9]+).json/\1/')
          BATCH_FILENAME="batch_${{ matrix.batch_number }}_of_${TOTAL_BATCHES}.json"
          echo "filename=${BATCH_FILENAME}" >> $GITHUB_OUTPUT

      - name: Process batch
        run: node fix-match-dates.js process ${{ steps.batch_file.outputs.filename }}

      - name: Commit results
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add results/results_batch_${{ matrix.batch_number }}.json
          git commit -m "Process batch ${{ steps.batch_file.outputs.filename }} [$(date -u +'%Y-%m-%dT%H:%M:%SZ')]" || echo "No changes to commit"
          git push

  merge-results:
    if: github.event.inputs.action == 'merge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Merge results
        run: node fix-match-dates.js merge

      - name: Commit merged results
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add dateFixes.json blocked.json
          git commit -m "Merge all batch results [$(date -u +'%Y-%m-%dT%H:%M:%SZ')]" || echo "No changes to commit"
          git push
