name: Process All Match Dates

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'process-all'
        type: choice
        options:
          - process-all
          - merge

jobs:
  count-batches:
    if: github.event.inputs.action == 'process-all'
    runs-on: ubuntu-latest
    outputs:
      total_batches: ${{ steps.get_count.outputs.count }}

    steps:
      - uses: actions/checkout@v3

      - name: Count batch files
        id: get_count
        run: |
          BATCH_COUNT=$(ls -1 batches/ | grep -c "batch_.*\.json" || echo "0")
          echo "Found ${BATCH_COUNT} batch files"
          echo "count=${BATCH_COUNT}" >> $GITHUB_OUTPUT

  process-dates:
    if: github.event.inputs.action == 'process-all'
    needs: count-batches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch_number: ${{ fromJson(format('[{0}]', join(range(1, add(fromJson(needs.count-batches.outputs.total_batches), 1)), ','))) }}
      # Process up to 5 batches in parallel
      max-parallel: 5
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Determine batch filename
        id: batch_file
        run: |
          TOTAL_BATCHES=${{ needs.count-batches.outputs.total_batches }}
          BATCH_FILENAME="batch_${{ matrix.batch_number }}_of_${TOTAL_BATCHES}.json"
          echo "filename=${BATCH_FILENAME}" >> $GITHUB_OUTPUT

      - name: Process batch
        run: node fix-match-dates.js process ${{ steps.batch_file.outputs.filename }}

      - name: Commit results
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git pull origin main # Pull latest changes to avoid conflicts
          git add results/
          git commit -m "Process batch ${{ steps.batch_file.outputs.filename }} [$(date -u +'%Y-%m-%dT%H:%M:%SZ')]" || echo "No changes to commit"
          git push

  merge-results:
    if: github.event.inputs.action == 'merge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Merge results
        run: node fix-match-dates.js merge

      - name: Commit merged results
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add dateFixes.json blocked.json
          git commit -m "Merge all batch results [$(date -u +'%Y-%m-%dT%H:%M:%SZ')]" || echo "No changes to commit"
          git push
